// WebApp/src/views/PaymentScreen.vue
<template>
  <PageContainer>
    <v-card class="mx-auto my-6" max-width="500" outlined>
      <v-card-title class="text-h6">Payment</v-card-title>
      <v-card-text>
        <p class="mb-4">Complete your payment for the service below:</p>

        <!-- Payment Summary -->
        <v-card outlined class="pa-4 mb-4">
          <div class="d-flex justify-space-between mb-2">
            <span>Client Name:</span>
            <strong>{{ clientUsername }}</strong>
          </div>
          <div class="d-flex justify-space-between mb-2">
            <span>Booking ID:</span>
            <strong>{{ bookingId }}</strong>
          </div>
          <div class='d-flex justify-space-between mb-2'>
            <span>Job Description:</span>
            <strong>{{ jobDes }}</strong>
          </div>
          <div class="d-flex justify-space-between mb-2">
            <span>Amount:</span>
            <strong>R {{ amount.toFixed(2) }}</strong>
          </div>
        </v-card>

        <!-- Payment Method -->
        <v-select
          v-model="paymentMethod"
          :items="paymentMethods"
          label="Select Payment Method"
          outlined
          required
        />

        <!-- Card Info -->
        <div v-if="paymentMethod === 'Card'" class="mt-4">
          <InputField v-model="cardNumber" label="Card Number" type="text" required />
          <div class="d-flex mt-2">
            <InputField v-model="expiry" label="Expiry MM/YY" type="text" class="mr-2" required />
            <InputField v-model="cvv" label="CVV" type="password" required />
          </div>
          <InputField v-model="cardHolder" label="Cardholder Name" type="text" required class="mt-2"/>
        </div>

      </v-card-text>

      <v-card-actions class="d-flex justify-center">
        <Button
          label="Pay Now"
          color="primary"
          :loading="loading"
          :disabled="!isFormValid"
          @click="processPayment"
        />
      </v-card-actions>
    </v-card>

    <!-- Success Snackbar -->
    <v-snackbar v-model="paymentSuccess" timeout="4000" color="green">
      Payment successful!
      <template #action="{ attrs }">
        <v-btn text v-bind="attrs" @click="paymentSuccess = false">Close</v-btn>
      </template>
    </v-snackbar>

    <!-- Error Snackbar -->
    <v-snackbar v-model="paymentError" timeout="4000" color="red">
      Payment failed. Try again.
      <template #action="{ attrs }">
        <v-btn text v-bind="attrs" @click="paymentError = false">Close</v-btn>
      </template>
    </v-snackbar>
  </PageContainer>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import PageContainer from '@/components/PageContainer.vue';
import InputField from '@/components/InputField.vue';
import Button from '@/components/Button.vue';
import apiService from '@/api/apiService';

// Router
const route = useRoute();
const router = useRouter();

// Query params
const bookingId = (route.query.bookingId as string) || '';
const jobDes = (route.query.jobDes as string) || '';
const amount = parseFloat((route.query.amount as string) || '0');
const clientUsername = (route.query.clientUsername as string) || '';
const mechanicId = Number(route.query.mechanicId) || 0;
const carWashId = Number(route.query.carWashId) || 0;

// Payment state
const paymentMethod = ref<'Card' | 'Bank Transfer' | 'Mobile Money'>('Card');
const paymentMethods = ['Card', 'Bank Transfer', 'Mobile Money'];
const cardNumber = ref('');
const expiry = ref('');
const cvv = ref('');
const cardHolder = ref('');

const loading = ref(false);
const paymentSuccess = ref(false);
const paymentError = ref(false);

// Form validation
const isFormValid = computed(() => {
  if (!bookingId || !amount || !clientUsername || !paymentMethod.value) return false;
  if (paymentMethod.value === 'Card') {
    return !!(cardNumber.value && expiry.value && cvv.value && cardHolder.value);
  }
  return true;
});

// Process payment
const processPayment = async () => {
  loading.value = true;

  try {
    const paymentPayload: any = {
      jobId: Number(bookingId),
      amount: amount,
      clientUsername: clientUsername,
    };

    // Assign mechanicId or carWashId based on job description
    if (jobDes.toLowerCase() !== "car wash service") {
      paymentPayload.mechanicId = mechanicId;
    } else {
      paymentPayload.carWashId = carWashId;
    }

    console.log("Payment payload being sent:", paymentPayload);

    // Send request
    const res = await apiService.createPayment(paymentPayload);

    console.log("Payment response:", res);

    paymentSuccess.value = true;

    router.push({
      name: "Payments",
      query: { bookingId }
    });
  } catch (err: any) {
    console.error("Payment failed:", err.response || err.message || err);
    paymentError.value = true;
  } finally {
    loading.value = false;
  }
};
</script>

<style scoped>
.v-card {
  border-radius: 12px;
  box-shadow: 0 2px 12px rgba(0,0,0,0.1);
}
</style>

// MobileApp/src/screens/shared/PaymentScreen.tsx
import React, { useState } from 'react';
import {
  View,
  Text,
  StyleSheet,
  TouchableOpacity,
  Alert,
  ScrollView,
  ActivityIndicator,
} from 'react-native';
import { CONFIG } from '../../config';
import apiService from '../../services/api';
import AsyncStorage from '@react-native-async-storage/async-storage';
import Icon from 'react-native-vector-icons/MaterialIcons';

const PaymentScreen = ({ route, navigation }: any) => {
  const { bookingId, amount, jobDes, mechanicId, carWashId, isCarWash } = route.params || {};
  const [paymentMethod, setPaymentMethod] = useState<'Bank Transfer' | 'Mobile Money' | 'Card'>('Bank Transfer');
  const [loading, setLoading] = useState(false);

  const [user, setUser] = useState<{ username?: string } | null>(null);
  React.useEffect(() => {
    AsyncStorage.getItem('user').then((s) => {
      if (s) setUser(JSON.parse(s));
    });
  }, []);

  const clientUsername = user?.username || '';
  const methods: Array<'Bank Transfer' | 'Mobile Money' | 'Card'> = ['Bank Transfer', 'Mobile Money', 'Card'];

  const processPayment = async () => {
    if (!bookingId || !amount || !clientUsername || loading) return;
    setLoading(true);
    try {
      const payload: any = { jobId: bookingId, amount: Number(amount), clientUsername };
      if (mechanicId) payload.mechanicId = mechanicId;
      if (carWashId) payload.carWashId = carWashId;
      if (isCarWash && !carWashId) {
        const bookingRes = await apiService.getCarWashBookingById(bookingId);
        const b = bookingRes.data;
        if (b?.carWashId) payload.carWashId = b.carWashId;
      }

      if (paymentMethod === 'Card') {
        Alert.alert('Card Payment', 'Card payments require Stripe. Use Bank Transfer or Mobile Money for now.');
        setLoading(false);
        return;
      }

      await apiService.createPayment(payload);

      if (!isCarWash && mechanicId) {
        await apiService.updateJob(bookingId, { status: 'paid', mechanicId });
      } else if (isCarWash) {
        const bookingRes = await apiService.getCarWashBookingById(bookingId);
        const booking = bookingRes.data;
        if (booking) {
          const carWashIdForPayment = carWashId || booking.carWashId;
          if (carWashIdForPayment && !payload.carWashId) payload.carWashId = carWashIdForPayment;
          booking.status = 'paid';
          await apiService.updateCarWashBooking(bookingId, booking);
        }
      }

      Alert.alert('Success', 'Payment recorded successfully.', [
        { text: 'OK', onPress: () => navigation.goBack() },
      ]);
    } catch (err: any) {
      Alert.alert('Error', err.message || 'Payment failed');
    } finally {
      setLoading(false);
    }
  };

  const formatCurrency = (val: number) => `R ${Number(val).toFixed(2)}`;

  return (
    <ScrollView style={styles.container} contentContainerStyle={styles.content}>
      <Text style={styles.title}>Payment</Text>
      <Text style={styles.subtitle}>Complete your payment for the service below</Text>

      <View style={styles.summary}>
        <View style={styles.row}>
          <Text>Client:</Text>
          <Text style={styles.bold}>{clientUsername}</Text>
        </View>
        <View style={styles.row}>
          <Text>Booking ID:</Text>
          <Text style={styles.bold}>{bookingId}</Text>
        </View>
        <View style={styles.row}>
          <Text>Description:</Text>
          <Text style={styles.bold}>{jobDes || 'Service'}</Text>
        </View>
        <View style={styles.row}>
          <Text>Amount:</Text>
          <Text style={styles.bold}>{formatCurrency(Number(amount))}</Text>
        </View>
      </View>

      <Text style={styles.methodLabel}>Payment Method</Text>
      {methods.map((m) => (
        <TouchableOpacity
          key={m}
          style={[styles.methodOption, paymentMethod === m && styles.methodOptionActive]}
          onPress={() => setPaymentMethod(m)}
        >
          <Icon name={m === 'Card' ? 'credit-card' : m === 'Mobile Money' ? 'phone-android' : 'account-balance'} size={24} color={paymentMethod === m ? '#fff' : CONFIG.COLORS.GRAY} />
          <Text style={[styles.methodText, paymentMethod === m && styles.methodTextActive]}>{m}</Text>
        </TouchableOpacity>
      ))}

      <TouchableOpacity
        style={[styles.button, loading && styles.buttonDisabled]}
        onPress={processPayment}
        disabled={loading}
      >
        {loading ? (
          <ActivityIndicator color="#fff" />
        ) : (
          <Text style={styles.buttonText}>Confirm Payment</Text>
        )}
      </TouchableOpacity>
    </ScrollView>
  );
};

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: CONFIG.COLORS.LIGHT_GRAY },
  content: { padding: CONFIG.DIMENSIONS.PADDING },
  title: { fontSize: CONFIG.FONT_SIZES.TITLE, fontWeight: 'bold', marginBottom: 8 },
  subtitle: { fontSize: CONFIG.FONT_SIZES.MEDIUM, color: CONFIG.COLORS.GRAY, marginBottom: 24 },
  summary: { backgroundColor: '#fff', padding: 16, borderRadius: 8, marginBottom: 24 },
  row: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 8 },
  bold: { fontWeight: '600' },
  methodLabel: { fontSize: CONFIG.FONT_SIZES.LARGE, fontWeight: '600', marginBottom: 12 },
  methodOption: { flexDirection: 'row', alignItems: 'center', padding: 16, backgroundColor: '#fff', borderRadius: 8, marginBottom: 8, gap: 12 },
  methodOptionActive: { backgroundColor: CONFIG.COLORS.PRIMARY },
  methodText: { fontSize: CONFIG.FONT_SIZES.MEDIUM },
  methodTextActive: { color: '#fff', fontWeight: '600' },
  button: { backgroundColor: CONFIG.COLORS.PRIMARY, padding: 16, borderRadius: 8, alignItems: 'center', marginTop: 24 },
  buttonDisabled: { opacity: 0.7 },
  buttonText: { color: '#fff', fontSize: CONFIG.FONT_SIZES.LARGE, fontWeight: '600' },
});

export default PaymentScreen;
